<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password field</name>
   <tag></tag>
   <elementGuidId>b28fcb31-5657-4bf9-ae7f-ccf4d2a4af83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'q-field__native q-placeholder' and @tabindex = '0' and @type = 'password']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_aef75d1e-dac2-4885-8d83-92e4d57237fe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_aef75d1e-dac2-4885-8d83-92e4d57237fe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1464d37-534a-48cc-a5e8-4fc3efe108d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>095f57c1-e5b2-498d-89c8-e5838100dabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f0ac6714-56e0-4d9b-a96b-dd147fa16b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_aef75d1e-dac2-4885-8d83-92e4d57237fe</value>
      <webElementGuid>56e54986-3463-4de9-86b3-2849d6938b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3e76418d-c21f-4cee-bba2-732ee20d3df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_aef75d1e-dac2-4885-8d83-92e4d57237fe&quot;)</value>
      <webElementGuid>fe505a18-9035-41a4-9c8f-9b21a68ca726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_aef75d1e-dac2-4885-8d83-92e4d57237fe']</value>
      <webElementGuid>954c70fe-e52f-4414-a177-276724c0a68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/main/div/form/div/div[2]/label/div/div/div/input</value>
      <webElementGuid>942c63ca-bd43-41fb-a617-505c867fc2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div/div/div/input</value>
      <webElementGuid>c494a8e2-3cce-453a-8968-2680df77610f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_aef75d1e-dac2-4885-8d83-92e4d57237fe' and @type = 'password']</value>
      <webElementGuid>d6ead3da-7bef-409b-93b5-348cba46a616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
