<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Username field</name>
   <tag></tag>
   <elementGuidId>53261a25-99aa-4bd3-99ec-2a7f84b4c07a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'q-field__native q-placeholder' and @tabindex = '0']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_24eab2dc-39cb-4a42-8b6b-f22e7e376562'</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_24eab2dc-39cb-4a42-8b6b-f22e7e376562</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca7e2e10-4420-469d-bf3f-179a29196dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>6c570a29-5686-4948-889f-444f55ac446e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f739702-f007-440e-abd3-cf3773f0daf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_24eab2dc-39cb-4a42-8b6b-f22e7e376562</value>
      <webElementGuid>429a3868-1256-4991-9b25-31c6095daddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30bec9cd-7b6f-4903-b604-a9f6dd11c84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_24eab2dc-39cb-4a42-8b6b-f22e7e376562&quot;)</value>
      <webElementGuid>2142ec05-d4ce-4f5d-b6ab-dc8e2d2f584a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_24eab2dc-39cb-4a42-8b6b-f22e7e376562']</value>
      <webElementGuid>2d6bdd20-58be-4994-8cd3-7ec21b2a224a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/main/div/form/div/div/label/div/div/div/input</value>
      <webElementGuid>cf2459b3-f7a2-46dc-9b6c-92bf9a85c6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c2e09678-e104-4c7a-9ecc-ae97f8b3e39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_24eab2dc-39cb-4a42-8b6b-f22e7e376562' and @type = 'text']</value>
      <webElementGuid>b56457b1-23d1-440a-ae41-59ef84be5765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
