<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password field</name>
   <tag></tag>
   <elementGuidId>9557cd8b-9ca8-47b8-83ea-e57c68eac0cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f_aef75d1e-dac2-4885-8d83-92e4d57237fe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_aef75d1e-dac2-4885-8d83-92e4d57237fe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>857deb75-8a09-4342-b2f2-b49b4c2961f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>97ad8d75-0a12-48fc-9202-27336f13bd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1eca6ba2-32b5-4c2c-9476-f3272062d331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_aef75d1e-dac2-4885-8d83-92e4d57237fe</value>
      <webElementGuid>eb372da0-6708-4a55-b4ca-f8337f7293a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1457559c-d6f1-4f68-bd3e-fcccc7bceb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_aef75d1e-dac2-4885-8d83-92e4d57237fe&quot;)</value>
      <webElementGuid>80e6ce21-6e56-4121-a3a9-f0a3e9d013d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_aef75d1e-dac2-4885-8d83-92e4d57237fe']</value>
      <webElementGuid>e3918272-4172-4a9f-9ebc-df4c65b0ce8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/main/div/form/div/div[2]/label/div/div/div/input</value>
      <webElementGuid>3a06bf55-9245-47dc-94d8-11f72d579ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div/div/div/input</value>
      <webElementGuid>b16b3ea3-a4b1-4c34-827b-2064c9f4d670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_aef75d1e-dac2-4885-8d83-92e4d57237fe' and @type = 'password']</value>
      <webElementGuid>bc6d5238-3f81-4a8f-9e9f-f04d7d0ca7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
